USE [master]
GO

/****** Object:  Database [TPASP.NET]    Script Date: 31/05/2022 01:18:36 ******/
CREATE DATABASE [TPASP.NET]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TPASP.NET', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TPASP.NET.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TPASP.NET_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TPASP.NET_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TPASP.NET].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TPASP.NET] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TPASP.NET] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TPASP.NET] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TPASP.NET] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TPASP.NET] SET ARITHABORT OFF 
GO

ALTER DATABASE [TPASP.NET] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TPASP.NET] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TPASP.NET] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TPASP.NET] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TPASP.NET] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TPASP.NET] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TPASP.NET] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TPASP.NET] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TPASP.NET] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TPASP.NET] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TPASP.NET] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TPASP.NET] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TPASP.NET] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TPASP.NET] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TPASP.NET] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TPASP.NET] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TPASP.NET] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TPASP.NET] SET RECOVERY FULL 
GO

ALTER DATABASE [TPASP.NET] SET  MULTI_USER 
GO

ALTER DATABASE [TPASP.NET] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TPASP.NET] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TPASP.NET] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TPASP.NET] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TPASP.NET] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TPASP.NET] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TPASP.NET] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TPASP.NET] SET  READ_WRITE 
GO

